name: CI

on:
  push:
    branches: [ master ]
    
env: 
  IMAGE_ID: ghcr.io/${{ github.repository }}:master

jobs:
  master-ci:
    name: Master push CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build and push
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ${{ env.IMAGE_ID }}
